//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VUA_api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VUA_api.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neužpildyti laukai.
        /// </summary>
        internal static string BlankFields {
            get {
                return ResourceManager.GetString("BlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra BUS.
        /// </summary>
        internal static string BUS {
            get {
                return ResourceManager.GetString("BUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paliko komentarą:.
        /// </summary>
        internal static string DataNodeComment {
            get {
                return ResourceManager.GetString("DataNodeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarai: .
        /// </summary>
        internal static string DataNodeComments {
            get {
                return ResourceManager.GetString("DataNodeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinimas: .
        /// </summary>
        internal static string DataNodeEvaluation {
            get {
                return ResourceManager.GetString("DataNodeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektas nerastas.
        /// </summary>
        internal static string DataNodeNotFound {
            get {
                return ResourceManager.GetString("DataNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepasirinkote dėstytojo.
        /// </summary>
        internal static string DidntChooseLecturer {
            get {
                return ResourceManager.GetString("DidntChooseLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepasirinkote dalyko.
        /// </summary>
        internal static string DidntChooseSubject {
            get {
                return ResourceManager.GetString("DidntChooseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prašome užpildyti visus formoje esančius laukus..
        /// </summary>
        internal static string FillInAllFields {
            get {
                return ResourceManager.GetString("FillInAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  iš 5.
        /// </summary>
        internal static string From5 {
            get {
                return ResourceManager.GetString("From5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėstytojo vardas: .
        /// </summary>
        internal static string LecturerName {
            get {
                return ResourceManager.GetString("LecturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lecturers.json.
        /// </summary>
        internal static string LecturersJson {
            get {
                return ResourceManager.GetString("LecturersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra privalomasis.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinimų skaičius: .
        /// </summary>
        internal static string NumberOfReviews {
            get {
                return ResourceManager.GetString("NumberOfReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra pasirenkamasis.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: .
        /// </summary>
        internal static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  įvertinęs: .
        /// </summary>
        internal static string ReviewScore {
            get {
                return ResourceManager.GetString("ReviewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to įvertinimas: .
        /// </summary>
        internal static string ReviewScore1 {
            get {
                return ResourceManager.GetString("ReviewScore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vartotojas: .
        /// </summary>
        internal static string ReviewUsername {
            get {
                return ResourceManager.GetString("ReviewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite fakultetą.
        /// </summary>
        internal static string SelectFaculty {
            get {
                return ResourceManager.GetString("SelectFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - esu visiškai nepatenkintas dėstytojo darbu..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - mokomasis dalykas labai sudomino ir paliko didelį įspūdį..
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - esu matęs kur kas geresnių dėstytojų....
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - dėstytojas didelio įspūdžio nepaliko..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - dėstytojas gerai dirba savo darbą, bet vis dėlto šio to pasigedau..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - dėstytojas puikiai išmano dėstomą dalyką ir geba informaciją pateikti labai aiškiai ir nuosekliai..
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - mokomasis dalykas visiškai nepateisino lūkesčių..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - buvo įdomių paskaitų, bet vis dėlto nerekomenduočiau..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - mokomasis dalykas naudingas, tačiau sužavėtas nelikau..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - naudingas bei įdomus dalykas..
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalyko pavadinimas: .
        /// </summary>
        internal static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subjects.json.
        /// </summary>
        internal static string SubjectsJson {
            get {
                return ResourceManager.GetString("SubjectsJson", resourceCulture);
            }
        }
    }
}
