//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VUA_App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VUA_App.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėstytojas jau buvo įvertintas.
        /// </summary>
        internal static string AlreadyEvaluatedLecturer {
            get {
                return ResourceManager.GetString("AlreadyEvaluatedLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas jau buvo įvertintas.
        /// </summary>
        internal static string AlreadyEvaluatedSubject {
            get {
                return ResourceManager.GetString("AlreadyEvaluatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonimas.
        /// </summary>
        internal static string AnonymousUser {
            get {
                return ResourceManager.GetString("AnonymousUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biologija.
        /// </summary>
        internal static string Biology {
            get {
                return ResourceManager.GetString("Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neužpildyti laukai.
        /// </summary>
        internal static string BlankFields {
            get {
                return ResourceManager.GetString("BlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vadovaujančios pareigos.
        /// </summary>
        internal static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protmūšiuose žinau beveik visus atsakymus.
        /// </summary>
        internal static string BrainBattle {
            get {
                return ResourceManager.GetString("BrainBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra BUS.
        /// </summary>
        internal static string BUS {
            get {
                return ResourceManager.GetString("BUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paslaugų / produktų pardavimas.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parduočiau bet ką, net šaldytuvą Šiaurės Ašigalyje.
        /// </summary>
        internal static string BusinessMan {
            get {
                return ResourceManager.GetString("BusinessMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti registraciją.
        /// </summary>
        internal static string CancelRegCaption {
            get {
                return ResourceManager.GetString("CancelRegCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai norite atšaukti registraciją? Įvesti duomenys nebus išsaugoti..
        /// </summary>
        internal static string CancelRegistration {
            get {
                return ResourceManager.GetString("CancelRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai nenorite baigti testo?.
        /// </summary>
        internal static string CancelTest {
            get {
                return ResourceManager.GetString("CancelTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pradėti testą iš naujo.
        /// </summary>
        internal static string CancelTestCaption {
            get {
                return ResourceManager.GetString("CancelTestCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negalima įvertinti dėstytojo.
        /// </summary>
        internal static string CantEvaluateLecturer {
            get {
                return ResourceManager.GetString("CantEvaluateLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negalima įvertinti dalyko.
        /// </summary>
        internal static string CantEvaluateSubject {
            get {
                return ResourceManager.GetString("CantEvaluateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite ar dalykas yra privalomasis, ar pasirenkamasis.
        /// </summary>
        internal static string ChooseOptionalOrMandatory {
            get {
                return ResourceManager.GetString("ChooseOptionalOrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duomenys sėkmingai atnaujinti..
        /// </summary>
        internal static string DataChangedSuccessfully {
            get {
                return ResourceManager.GetString("DataChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paliko komentarą:.
        /// </summary>
        internal static string DataNodeComment {
            get {
                return ResourceManager.GetString("DataNodeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarai: .
        /// </summary>
        internal static string DataNodeComments {
            get {
                return ResourceManager.GetString("DataNodeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinimas: .
        /// </summary>
        internal static string DataNodeEvaluation {
            get {
                return ResourceManager.GetString("DataNodeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektas nerastas.
        /// </summary>
        internal static string DataNodeNotFound {
            get {
                return ResourceManager.GetString("DataNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai norite pašalinti šią anketą?.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anketos  šalinimas.
        /// </summary>
        internal static string DeleteUserCaption {
            get {
                return ResourceManager.GetString("DeleteUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepasirinkote dėstytojo.
        /// </summary>
        internal static string DidntChooseLecturer {
            get {
                return ResourceManager.GetString("DidntChooseLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepasirinkote dalyko.
        /// </summary>
        internal static string DidntChooseSubject {
            get {
                return ResourceManager.GetString("DidntChooseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaip atrodytų Tavo svajonių darbas.
        /// </summary>
        internal static string DreamJob {
            get {
                return ResourceManager.GetString("DreamJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekonomika.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo el. paštas.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite vardą ir pavardę..
        /// </summary>
        internal static string EnterNameAndUsername {
            get {
                return ResourceManager.GetString("EnterNameAndUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertintas dėstytojas: .
        /// </summary>
        internal static string EvaluatedLecturer {
            get {
                return ResourceManager.GetString("EvaluatedLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinti dėstytojai:.
        /// </summary>
        internal static string EvaluatedLecturers {
            get {
                return ResourceManager.GetString("EvaluatedLecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertintas dalykas: .
        /// </summary>
        internal static string EvaluatedSubject {
            get {
                return ResourceManager.GetString("EvaluatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinti dalykai:.
        /// </summary>
        internal static string EvaluatedSubjects {
            get {
                return ResourceManager.GetString("EvaluatedSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertinimas.
        /// </summary>
        internal static string EvaluationCaption {
            get {
                return ResourceManager.GetString("EvaluationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fakulteto.
        /// </summary>
        internal static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prašome užpildyti visus formoje esančius laukus..
        /// </summary>
        internal static string FillInAllFields {
            get {
                return ResourceManager.GetString("FillInAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galiu sutaisyti sugedusius elektros prietaisus.
        /// </summary>
        internal static string FixBrokenThings {
            get {
                return ResourceManager.GetString("FixBrokenThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laisvas darbo grafikas.
        /// </summary>
        internal static string FlexibleWorkingHours {
            get {
                return ResourceManager.GetString("FlexibleWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užsienio kalbos.
        /// </summary>
        internal static string ForeignLanguages {
            get {
                return ResourceManager.GetString("ForeignLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iš.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  iš 5.
        /// </summary>
        internal static string From5 {
            get {
                return ResourceManager.GetString("From5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagalba pagyvenusiems žmonėms.
        /// </summary>
        internal static string HelpOldPeople {
            get {
                return ResourceManager.GetString("HelpOldPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istorija.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaip atrodo....
        /// </summary>
        internal static string HowDoesItLook {
            get {
                return ResourceManager.GetString("HowDoesItLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo laboratorija.
        /// </summary>
        internal static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbas laboratorijoje.
        /// </summary>
        internal static string LaboratoryJob {
            get {
                return ResourceManager.GetString("LaboratoryJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėstytojo vardas: .
        /// </summary>
        internal static string LecturerName {
            get {
                return ResourceManager.GetString("LecturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dėstytojai:.
        /// </summary>
        internal static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo laisvalaikis.
        /// </summary>
        internal static string Leisure {
            get {
                return ResourceManager.GetString("Leisure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paskaitos/pamokos, į kurias mielai eitum.
        /// </summary>
        internal static string LikedSubjects {
            get {
                return ResourceManager.GetString("LikedSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisijungimas.
        /// </summary>
        internal static string LogInCaption {
            get {
                return ResourceManager.GetString("LogInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra privalomasis.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketingas.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matematika.
        /// </summary>
        internal static string Math {
            get {
                return ResourceManager.GetString("Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveris yra nepasiekiamas.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekomenduojamų studijų programų nėra..
        /// </summary>
        internal static string NoRecommendedProgrammes {
            get {
                return ResourceManager.GetString("NoRecommendedProgrammes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvertinimų skaičius: .
        /// </summary>
        internal static string NumberOfReviews {
            get {
                return ResourceManager.GetString("NumberOfReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbas ofise.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalykas yra pasirenkamasis.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo vakarėliai.
        /// </summary>
        internal static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slaptažodis pakeistas sėkmingai..
        /// </summary>
        internal static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvesti slaptažodžiai nesutampa. Prašome įvesti juos dar kartą..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failo vieta.
        /// </summary>
        internal static string PathCaption {
            get {
                return ResourceManager.GetString("PathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failas išsaugotas:.
        /// </summary>
        internal static string PathComment {
            get {
                return ResourceManager.GetString("PathComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizika.
        /// </summary>
        internal static string Physics {
            get {
                return ResourceManager.GetString("Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo augalai.
        /// </summary>
        internal static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groju muzikos instrumentu.
        /// </summary>
        internal static string PlayingInstrument {
            get {
                return ResourceManager.GetString("PlayingInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekomenduojamos studijų programos.
        /// </summary>
        internal static string RecommendedProgrammes {
            get {
                return ResourceManager.GetString("RecommendedProgrammes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėtas naujas dėstytojas: .
        /// </summary>
        internal static string RegisteredLecturer {
            get {
                return ResourceManager.GetString("RegisteredLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėtas naujas dalykas: .
        /// </summary>
        internal static string RegisteredSubject {
            get {
                return ResourceManager.GetString("RegisteredSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        internal static string RegistrationCaption {
            get {
                return ResourceManager.GetString("RegistrationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija sėkminga..
        /// </summary>
        internal static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesutampa slaptažodžiai.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyrinėjimai.
        /// </summary>
        internal static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: .
        /// </summary>
        internal static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  įvertinęs: .
        /// </summary>
        internal static string ReviewScore {
            get {
                return ResourceManager.GetString("ReviewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vartotojas: .
        /// </summary>
        internal static string ReviewUsername {
            get {
                return ResourceManager.GetString("ReviewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite fakultetą.
        /// </summary>
        internal static string SelectFaculty {
            get {
                return ResourceManager.GetString("SelectFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodomi .
        /// </summary>
        internal static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užkalbinti nepažįstamą žmogų man yra vieni juokai.
        /// </summary>
        internal static string Sociable {
            get {
                return ResourceManager.GetString("Sociable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - esu visiškai nepatenkintas dėstytojo darbu..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - mokomasis dalykas labai sudomino ir paliko didelį įspūdį..
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - esu matęs kur kas geresnių dėstytojų....
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - dėstytojas didelio įspūdžio nepaliko..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - dėstytojas gerai dirba savo darbą, bet vis dėlto šio to pasigedau..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - dėstytojas puikiai išmano dėstomą dalyką ir geba informaciją pateikti labai aiškiai ir nuosekliai..
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - mokomasis dalykas visiškai nepateisino lūkesčių..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - buvo įdomių paskaitų, bet vis dėlto nerekomenduočiau..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - mokomasis dalykas naudingas, tačiau sužavėtas nelikau..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - naudingas bei įdomus dalykas..
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalyko pavadinimas: .
        /// </summary>
        internal static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dalykai.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anketa pašalinta sėkmingai..
        /// </summary>
        internal static string SuccessfulDeletion {
            get {
                return ResourceManager.GetString("SuccessfulDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šalinimas sėkmingas.
        /// </summary>
        internal static string SuccessfulDeletionCaption {
            get {
                return ResourceManager.GetString("SuccessfulDeletionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dėstytojas sėkmingai įvertintas..
        /// </summary>
        internal static string SuccessfulLectEvaluation {
            get {
                return ResourceManager.GetString("SuccessfulLectEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisijungta sėkmingai..
        /// </summary>
        internal static string SuccessfulLogIn {
            get {
                return ResourceManager.GetString("SuccessfulLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokomasis dalykas sėkmingai įvertintas..
        /// </summary>
        internal static string SuccessfulSubjEvaluation {
            get {
                return ResourceManager.GetString("SuccessfulSubjEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavo talentas.
        /// </summary>
        internal static string Talent {
            get {
                return ResourceManager.GetString("Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darbas su technika.
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greitai perprantu naująsias technologijas.
        /// </summary>
        internal static string TechnologiesExpert {
            get {
                return ResourceManager.GetString("TechnologiesExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duomenys pakeisti.
        /// </summary>
        internal static string UpdateCaption {
            get {
                return ResourceManager.GetString("UpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvestas prisijungimo vardas jau egzistuoja..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naudotojas:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardas užimtas.
        /// </summary>
        internal static string UserNameExistsCaption {
            get {
                return ResourceManager.GetString("UserNameExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas prisijungimo vardas..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas vardas.
        /// </summary>
        internal static string UserNotFoundCaption {
            get {
                return ResourceManager.GetString("UserNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.json.
        /// </summary>
        internal static string UsersJson {
            get {
                return ResourceManager.GetString("UsersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.vu.lt/.
        /// </summary>
        internal static string VUpageLink {
            get {
                return ResourceManager.GetString("VUpageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingi duomenys.
        /// </summary>
        internal static string WrongArguments {
            get {
                return ResourceManager.GetString("WrongArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingi duomenys.
        /// </summary>
        internal static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas e-paštas.
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurodyto fakulteto nėra..
        /// </summary>
        internal static string WrongFaculty {
            get {
                return ResourceManager.GetString("WrongFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas slaptažodis. Bandykite dar kartą..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas slaptažodis.
        /// </summary>
        internal static string WrongPasswordCaption {
            get {
                return ResourceManager.GetString("WrongPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas telefono numeris. Telefono numerio formatas: +3706*******.
        /// </summary>
        internal static string WrongPhoneNo {
            get {
                return ResourceManager.GetString("WrongPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaunų žmonių problemų sprendimas.
        /// </summary>
        internal static string YouthProblems {
            get {
                return ResourceManager.GetString("YouthProblems", resourceCulture);
            }
        }
    }
}
